# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo 
    
    steps:
      - name: Get Start Timestamp
        id: startDate
        run: echo "::set-output name=startDate::$(date +"%Y%m%d%H%M%S")"    
      - name: Get End Timestamp
        id: endDate
        run: echo "::set-output name=endDate::$(date +"%Y%m%d%H%M%S")"    
      - name: Make GraphQL Request
        run: |
          curl -X POST -H "Authorization: UserAccessKey ${{secrets.VELOCITY_TOKEN}}" \
               -H "Content-Type: application/json" \
               -H "Accept: application/json" \
               --location https://velocity.apps.67a34e6d234e92463ac6bbee.eu1.techzone.ibm.com/release-events-api/graphql \
               -d '{
                   "query":"mutation {  uploadBuildData(    data: {      id: \"${{github.sha}}\"      name: \"${{github.sha}}\"      status: success      application: {        name: \"hybrid app z and distributed\"        id: \"f944a4a5-9880-4162-96df-cad629f7571b\"      }      url: \"https://github.com/vito490/containerized-app-demo/actions/runs/${{github.run_id}}\"      requestor: \"vito490\"      tenantId: \"5ade13625558f2c6688d15ce\"      revision: \"${{github.sha}}\"      startTime: \"${{ steps.startDate.outputs.startDate }}\" endTime: \"${{ steps.endDate.outputs.endDate }}\" versionName: \"${{github.sha}}\" }  ) {    _id    id    name    status    url    startTime    endTime    requestor    revision    number    labels    source    branch    parameters {      name      value      source    }    application {      id      externalId      name    }  }}",
                   "variables":{},
                   "operationName":null
                  }'
