# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo 
    
    steps:
      - name: Get Start Timestamp
        id: startDate
        run: echo "::set-output name=startDate::$( date +%s%N | cut -b1-13)"    
      - name: Get End Timestamp
        id: endDate
        run: echo "::set-output name=endDate::$( date +%s%N | cut -b1-13)"    
     
